"""social_login_migration

Revision ID: 07f2441fae7d
Revises: 
Create Date: 2025-11-24 17:44:35.282566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '07f2441fae7d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('analysis_cache', 'data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('analysis_cache', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('analysis_cache_cache_key_key', 'analysis_cache', type_='unique')
    op.drop_index('idx_cache_expires', table_name='analysis_cache')
    op.drop_index('idx_cache_key', table_name='analysis_cache')
    op.create_index(op.f('ix_analysis_cache_cache_key'), 'analysis_cache', ['cache_key'], unique=True)
    op.drop_table_comment(
        'analysis_cache',
        existing_comment='통계 분석 결과 캐시 (성능 최적화)',
        schema=None
    )
    op.alter_column('chat_history', 'tokens_used',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('chat_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_chat_history_session', table_name='chat_history')
    op.drop_index('idx_chat_history_user', table_name='chat_history')
    op.drop_table_comment(
        'chat_history',
        existing_comment='VIP 사용자 AI 채팅 대화 기록',
        schema=None
    )
    op.alter_column('credit_transactions', 'type',
               existing_type=postgresql.ENUM('purchase', 'prediction', 'ad_reward', 'referral', 'refund', name='transaction_type'),
               type_=sa.Enum('purchase', 'prediction', 'ad_reward', 'referral', 'refund', name='transactiontype'),
               existing_nullable=False)
    op.alter_column('credit_transactions', 'metadata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('credit_transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_transactions_type', table_name='credit_transactions')
    op.drop_index('idx_transactions_user', table_name='credit_transactions')
    op.drop_table_comment(
        'credit_transactions',
        existing_comment='크레딧 충전/사용/환불 거래 내역',
        schema=None
    )
    op.alter_column('lotto_draws', 'jackpot_winners',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('lotto_draws', 'jackpot_amount',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('lotto_draws', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_lotto_draws_date', table_name='lotto_draws')
    op.drop_index('idx_lotto_draws_round', table_name='lotto_draws')
    op.drop_constraint('lotto_draws_draw_date_key', 'lotto_draws', type_='unique')
    op.create_index(op.f('ix_lotto_draws_draw_date'), 'lotto_draws', ['draw_date'], unique=True)
    op.drop_table_comment(
        'lotto_draws',
        existing_comment='로또 회차별 당첨번호 및 상금 정보',
        schema=None
    )
    op.alter_column('payments', 'status',
               existing_type=postgresql.ENUM('pending', 'completed', 'failed', 'refunded', name='payment_status'),
               type_=sa.Enum('pending', 'completed', 'failed', 'refunded', name='paymentstatus'),
               nullable=False,
               existing_server_default=sa.text("'pending'::payment_status"))
    op.alter_column('payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_payments_status', table_name='payments')
    op.drop_index('idx_payments_transaction', table_name='payments')
    op.drop_index('idx_payments_user', table_name='payments')
    op.drop_table_comment(
        'payments',
        existing_comment='결제 거래 기록 (Toss, Kakao Pay 등)',
        schema=None
    )
    op.alter_column('predictions', 'prediction_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'standard'::character varying"))
    op.alter_column('predictions', 'matched_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('predictions', 'is_winner',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('predictions', 'prize_amount',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('predictions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_predictions_draw', table_name='predictions')
    op.drop_index('idx_predictions_strategy', table_name='predictions')
    op.drop_index('idx_predictions_user', table_name='predictions')
    op.drop_index('idx_predictions_winner', table_name='predictions', postgresql_where='(is_winner = true)')
    op.drop_table_comment(
        'predictions',
        existing_comment='사용자별 번호 예측 기록 및 결과',
        schema=None
    )
    op.alter_column('strategies', 'total_predictions',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('strategies', 'total_wins',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('strategies', 'win_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('strategies', 'avg_matched',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('strategies', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('strategies', 'requires_vip',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('strategies', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('strategies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_table_comment(
        'strategies',
        existing_comment='10가지 예측 전략 정보 및 통계',
        schema=None
    )
    op.alter_column('success_stories', 'is_anonymous',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('success_stories', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('success_stories', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_success_stories_public', table_name='success_stories', postgresql_where='(is_public = true)')
    op.drop_index('idx_success_stories_rank', table_name='success_stories')
    op.drop_table_comment(
        'success_stories',
        existing_comment='당첨 성공 사례 (마케팅용)',
        schema=None
    )
    op.alter_column('user_subscriptions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('user_subscriptions', 'auto_renewal',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('user_subscriptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_subscriptions_active', table_name='user_subscriptions', postgresql_where='(is_active = true)')
    op.drop_index('idx_subscriptions_expires', table_name='user_subscriptions')
    op.drop_index('idx_subscriptions_user', table_name='user_subscriptions')
    op.drop_table_comment(
        'user_subscriptions',
        existing_comment='Premium/VIP 구독 정보',
        schema=None
    )
    op.add_column('users', sa.Column('is_adult_verified', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('birth_year', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('birth_date', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('adult_verify_method', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('verified_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('terms_agreed_at', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('privacy_agreed_at', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('marketing_agreed', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('status', sa.String(length=20), nullable=False))
    op.alter_column('users', 'provider',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               nullable=False)
    op.alter_column('users', 'provider_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               nullable=False)
    op.alter_column('users', 'nickname',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'tier',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'free'::character varying"))
    op.alter_column('users', 'credits',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('3'))
    op.alter_column('users', 'ai_chat_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'monthly_ai_tokens_used',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_nickname', table_name='users')
    op.drop_index('idx_users_provider', table_name='users')
    op.drop_index('idx_users_tier', table_name='users')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_nickname_key', 'users', type_='unique')
    op.create_unique_constraint('uq_provider_user', 'users', ['provider', 'provider_id'])
    op.drop_table_comment(
        'users',
        existing_comment='사용자 계정 및 인증 정보',
        schema=None
    )
    op.drop_column('users', 'name')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'profile_image_url')
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('profile_image_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_table_comment(
        'users',
        '사용자 계정 및 인증 정보',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint('uq_provider_user', 'users', type_='unique')
    op.create_unique_constraint('users_nickname_key', 'users', ['nickname'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.create_index('idx_users_tier', 'users', ['tier'], unique=False)
    op.create_index('idx_users_provider', 'users', ['provider', 'provider_id'], unique=False)
    op.create_index('idx_users_nickname', 'users', ['nickname'], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'monthly_ai_tokens_used',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'ai_chat_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'credits',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('3'))
    op.alter_column('users', 'tier',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'free'::character varying"))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'nickname',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('users', 'provider_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'provider',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('users', 'status')
    op.drop_column('users', 'marketing_agreed')
    op.drop_column('users', 'privacy_agreed_at')
    op.drop_column('users', 'terms_agreed_at')
    op.drop_column('users', 'verified_at')
    op.drop_column('users', 'adult_verify_method')
    op.drop_column('users', 'birth_date')
    op.drop_column('users', 'birth_year')
    op.drop_column('users', 'is_adult_verified')
    op.create_table_comment(
        'user_subscriptions',
        'Premium/VIP 구독 정보',
        existing_comment=None,
        schema=None
    )
    op.create_index('idx_subscriptions_user', 'user_subscriptions', ['user_id'], unique=False)
    op.create_index('idx_subscriptions_expires', 'user_subscriptions', ['expires_at'], unique=False)
    op.create_index('idx_subscriptions_active', 'user_subscriptions', ['is_active'], unique=False, postgresql_where='(is_active = true)')
    op.alter_column('user_subscriptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user_subscriptions', 'auto_renewal',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('user_subscriptions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.create_table_comment(
        'success_stories',
        '당첨 성공 사례 (마케팅용)',
        existing_comment=None,
        schema=None
    )
    op.create_index('idx_success_stories_rank', 'success_stories', ['prize_rank'], unique=False)
    op.create_index('idx_success_stories_public', 'success_stories', ['is_public'], unique=False, postgresql_where='(is_public = true)')
    op.alter_column('success_stories', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('success_stories', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('success_stories', 'is_anonymous',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.create_table_comment(
        'strategies',
        '10가지 예측 전략 정보 및 통계',
        existing_comment=None,
        schema=None
    )
    op.alter_column('strategies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('strategies', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('strategies', 'requires_vip',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('strategies', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('strategies', 'avg_matched',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('strategies', 'win_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('strategies', 'total_wins',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('strategies', 'total_predictions',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_table_comment(
        'predictions',
        '사용자별 번호 예측 기록 및 결과',
        existing_comment=None,
        schema=None
    )
    op.create_index('idx_predictions_winner', 'predictions', ['is_winner'], unique=False, postgresql_where='(is_winner = true)')
    op.create_index('idx_predictions_user', 'predictions', ['user_id', sa.text('created_at DESC')], unique=False)
    op.create_index('idx_predictions_strategy', 'predictions', ['strategy_name'], unique=False)
    op.create_index('idx_predictions_draw', 'predictions', ['draw_number'], unique=False)
    op.alter_column('predictions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('predictions', 'prize_amount',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('predictions', 'is_winner',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('predictions', 'matched_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('predictions', 'prediction_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'standard'::character varying"))
    op.create_table_comment(
        'payments',
        '결제 거래 기록 (Toss, Kakao Pay 등)',
        existing_comment=None,
        schema=None
    )
    op.create_index('idx_payments_user', 'payments', ['user_id', sa.text('created_at DESC')], unique=False)
    op.create_index('idx_payments_transaction', 'payments', ['transaction_id'], unique=False)
    op.create_index('idx_payments_status', 'payments', ['status'], unique=False)
    op.alter_column('payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('payments', 'status',
               existing_type=sa.Enum('pending', 'completed', 'failed', 'refunded', name='paymentstatus'),
               type_=postgresql.ENUM('pending', 'completed', 'failed', 'refunded', name='payment_status'),
               nullable=True,
               existing_server_default=sa.text("'pending'::payment_status"))
    op.create_table_comment(
        'lotto_draws',
        '로또 회차별 당첨번호 및 상금 정보',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_lotto_draws_draw_date'), table_name='lotto_draws')
    op.create_unique_constraint('lotto_draws_draw_date_key', 'lotto_draws', ['draw_date'])
    op.create_index('idx_lotto_draws_round', 'lotto_draws', [sa.text('round DESC')], unique=False)
    op.create_index('idx_lotto_draws_date', 'lotto_draws', [sa.text('draw_date DESC')], unique=False)
    op.alter_column('lotto_draws', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('lotto_draws', 'jackpot_amount',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('lotto_draws', 'jackpot_winners',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_table_comment(
        'credit_transactions',
        '크레딧 충전/사용/환불 거래 내역',
        existing_comment=None,
        schema=None
    )
    op.create_index('idx_transactions_user', 'credit_transactions', ['user_id', sa.text('created_at DESC')], unique=False)
    op.create_index('idx_transactions_type', 'credit_transactions', ['type'], unique=False)
    op.alter_column('credit_transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('credit_transactions', 'metadata_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('credit_transactions', 'type',
               existing_type=sa.Enum('purchase', 'prediction', 'ad_reward', 'referral', 'refund', name='transactiontype'),
               type_=postgresql.ENUM('purchase', 'prediction', 'ad_reward', 'referral', 'refund', name='transaction_type'),
               existing_nullable=False)
    op.create_table_comment(
        'chat_history',
        'VIP 사용자 AI 채팅 대화 기록',
        existing_comment=None,
        schema=None
    )
    op.create_index('idx_chat_history_user', 'chat_history', ['user_id', sa.text('created_at DESC')], unique=False)
    op.create_index('idx_chat_history_session', 'chat_history', ['session_id', 'created_at'], unique=False)
    op.alter_column('chat_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('chat_history', 'tokens_used',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_table_comment(
        'analysis_cache',
        '통계 분석 결과 캐시 (성능 최적화)',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_analysis_cache_cache_key'), table_name='analysis_cache')
    op.create_index('idx_cache_key', 'analysis_cache', ['cache_key'], unique=False)
    op.create_index('idx_cache_expires', 'analysis_cache', ['expires_at'], unique=False)
    op.create_unique_constraint('analysis_cache_cache_key_key', 'analysis_cache', ['cache_key'])
    op.alter_column('analysis_cache', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('analysis_cache', 'data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    # ### end Alembic commands ###
